"""Smoke tests for the ownership-proof (SLIP-0019 / BIP-322) bindings.

These exercise the FFI through the high-level :class:`OwnershipProof` facade.
They run under any test runner (pytest) or standalone
(`python3 test_ownership_proof.py`). The shared library must be loadable (built
into c/build, or WABISABI_LIB / LD_LIBRARY_PATH pointing at it).

The scriptPubKey vectors below are derived from the deterministic private key
`KEY` (the same fixture the C# interop suite uses), so the whole test is
self-contained and needs no external Bitcoin library.
"""

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

# Public API only — the FFI plumbing in wabisabi._native is intentionally private.
from wabisabi import OwnershipProof, OwnershipScriptPubKeyType, WabiSabiError  # noqa: E402

# Deterministic key so failures are reproducible (matches the C# interop fixture).
KEY = bytes.fromhex("1122334455667788990011223344556677889900112233445566778899001122")
COMMITMENT = bytes([0xDE, 0xAD, 0xBE, 0xEF, 0x01, 0x02, 0x03])
IDENTIFIERS = [bytes(range(1, 33))]

# scriptPubKeys the owner of KEY spends from, per script type.
SPK = {
    OwnershipScriptPubKeyType.SEGWIT:
        bytes.fromhex("00143273dd7061fe87103921b09bf8dbe85a9fc55032"),
    OwnershipScriptPubKeyType.TAPROOT_BIP86:
        bytes.fromhex("512076014287324406ef69724b75d67730711b8573c1918e64b1b6b552edefd9fd6f"),
}

# Reference proof bytes produced by WalletWasabi's *managed* OwnershipProof for
# (KEY, COMMITMENT, IDENTIFIERS, user_confirmation=True), captured from the C#
# interop suite. Pinning them here guards byte-for-byte wire compatibility:
# a proof generated by these bindings must be identical to WalletWasabi's, so
# each side accepts the other's proofs.
WALLETWASABI_PROOF = {
    OwnershipScriptPubKeyType.SEGWIT: bytes.fromhex(
        "534c001901010102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
        "000247304402202cb52b6ff775e5591c9bdd2e7689d5bf6756b0c904eb9f9310e8461972a62e"
        "53022046eab36eb581410a3dc3813c352c16afa20e3d371b5436db106b0826cf6cd68f012103"
        "80038951df186d2f439aa633c332f30f1d78de48e09dddfbb42f6118bcc91170"),
    OwnershipScriptPubKeyType.TAPROOT_BIP86: bytes.fromhex(
        "534c001901010102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20"
        "0001403faf55b2524324c82b1899375e22546f500e6b87564b205180b85e23419969a121f679"
        "49bf4fceff0d418f24a89508af927725ce92713c84c583ff589e0a5b5a"),
}


def test_generation_matches_walletwasabi_bytes():
    """WabiSabi bindings generate byte-for-byte identical proofs to WalletWasabi."""
    for spk_type, expected in WALLETWASABI_PROOF.items():
        proof = OwnershipProof.generate(
            KEY, COMMITMENT, IDENTIFIERS, spk_type, user_confirmation=True)
        assert proof == expected, spk_type.name


def test_verifies_walletwasabi_proof():
    """WalletWasabi -> WabiSabi: a proof produced by WalletWasabi verifies here."""
    for spk_type, spk in SPK.items():
        ww_proof = WALLETWASABI_PROOF[spk_type]
        assert OwnershipProof.verify(
            ww_proof, spk, COMMITMENT, require_user_confirmation=True) is True


def test_generate_is_deterministic():
    for spk_type in SPK:
        a = OwnershipProof.generate(KEY, COMMITMENT, IDENTIFIERS, spk_type)
        b = OwnershipProof.generate(KEY, COMMITMENT, IDENTIFIERS, spk_type)
        assert a == b
        assert len(a) > 0


def test_generate_then_verify_roundtrip():
    for spk_type, spk in SPK.items():
        proof = OwnershipProof.generate(
            KEY, COMMITMENT, IDENTIFIERS, spk_type, user_confirmation=True)
        assert OwnershipProof.verify(
            proof, spk, COMMITMENT, require_user_confirmation=True) is True


def test_verify_rejects_wrong_commitment():
    for spk_type, spk in SPK.items():
        proof = OwnershipProof.generate(KEY, COMMITMENT, IDENTIFIERS, spk_type)
        assert OwnershipProof.verify(proof, spk, b"not-the-commitment", False) is False


def test_verify_rejects_wrong_scriptpubkey():
    proof = OwnershipProof.generate(
        KEY, COMMITMENT, IDENTIFIERS, OwnershipScriptPubKeyType.SEGWIT)
    other_spk = SPK[OwnershipScriptPubKeyType.TAPROOT_BIP86]
    assert OwnershipProof.verify(proof, other_spk, COMMITMENT, False) is False


def test_verify_require_user_confirmation():
    spk_type = OwnershipScriptPubKeyType.SEGWIT
    spk = SPK[spk_type]
    proof = OwnershipProof.generate(
        KEY, COMMITMENT, IDENTIFIERS, spk_type, user_confirmation=False)
    # Valid when we don't require the flag...
    assert OwnershipProof.verify(proof, spk, COMMITMENT, require_user_confirmation=False) is True
    # ...but rejected when we do.
    assert OwnershipProof.verify(proof, spk, COMMITMENT, require_user_confirmation=True) is False


def test_verify_malformed_proof_raises():
    spk = SPK[OwnershipScriptPubKeyType.SEGWIT]
    try:
        OwnershipProof.verify(b"\x00\x01\x02", spk, COMMITMENT, False)
    except WabiSabiError:
        pass
    else:
        raise AssertionError("expected an error for a malformed proof")


def test_generate_rejects_bad_key_length():
    try:
        OwnershipProof.generate(b"\x00" * 31, COMMITMENT, IDENTIFIERS)
    except ValueError:
        pass
    else:
        raise AssertionError("expected ValueError for a short key")


def test_no_identifiers_and_no_commitment():
    spk_type = OwnershipScriptPubKeyType.SEGWIT
    spk = SPK[spk_type]
    proof = OwnershipProof.generate(KEY, script_pubkey_type=spk_type)
    assert OwnershipProof.verify(proof, spk) is True


def _run_standalone():
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failed = 0
    for fn in fns:
        try:
            fn()
            print(f"PASS {fn.__name__}")
        except Exception as exc:  # noqa: BLE001
            failed += 1
            print(f"FAIL {fn.__name__}: {exc!r}")
    if failed:
        print(f"\n{failed}/{len(fns)} tests failed")
        sys.exit(1)
    print(f"\nall {len(fns)} tests passed")


if __name__ == "__main__":
    _run_standalone()
